spring.application.name=interfaz-backend
# ===============================
# PostgreSQL DataSource
# ===============================
spring.datasource.postgres.jdbc-url=jdbc:postgresql://127.0.0.1:5434/interfaz_contable_db
spring.datasource.postgres.username=app_interfaz_contable
spring.datasource.postgres.password=interfaz2022#
spring.datasource.postgres.driver-class-name=org.postgresql.Driver
# ===============================
# HikariCP Pool - Postgres
# ===============================
spring.datasource.postgres.hikari.maximum-pool-size=10
spring.datasource.postgres.hikari.minimum-idle=10
spring.datasource.postgres.hikari.idle-timeout=30000
spring.datasource.postgres.hikari.pool-name=PostgresHikariCP

# =====================================================
# JDBC TEMPLATE
# =====================================================

spring.jdbc.template.fetch-size=100
spring.jdbc.template.max-rows=500


# =====================================================
# SQL INITIALIZATION (comentado)
# =====================================================

#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:sql/db.sql


# =====================================================
# LOGGING
# =====================================================

# Logs HTTP
logging.level.org.springframework.web=DEBUG

# Logs JDBC
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.support=DEBUG
#logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE


# =====================================================
# SERVER ERROR DETAILS (DEV)
# =====================================================

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# =====================================================
# SECURITY - PASSWORD POLICIES
# =====================================================

security.password.history-limit=25
security.password.max-age-days=30


# =====================================================
# SECURITY - SESSION MANAGEMENT
# =====================================================

security.sesion.max-active-sessions=1
security.sesion.inactivity-minutes=5
security.sesion.max-failed-attempts=5


# =====================================================
# PASSWORD EXPIRATION SCHEDULER
# =====================================================

# Todos los días a las 12:00 AM (medianoche)
#security.password.expiration-cron=0 0 0 * * *

# Cada 30 segundos (DEV / pruebas)
security.password.expiration-cron=*/30 * * * * *
security.password.expiration-zone=America/Bogota


# =====================================================
# NO-LOGIN / ACCOUNT STATUS SCHEDULERS
# =====================================================

# Suspende usuarios sin login (diario a medianoche)
security.login.suspend-cron=0 0 0 * * *
security.login.suspend-days=30

# Inactiva usuarios sin login (00:10 AM)
security.login.inactivate-cron=0 10 0 * * *
security.login.inactivate-days=60

security.login.zone=America/Bogota

spring.main.lazy-initialization=true
logging.level.org.springframework.security=DEBUG